background_opacity 1.0

window_padding_width 0

scrollback_lines 100000

font_family DejaVuSansM Nerd Font Mono
bold_font DejaVuSansM Nerd Font Mono Bold
italic_font DejaVuSansM Nerd Font Mono Italic
bold_italic_font DejaVuSansM Nerd Font Mono Bold Italic
font_size 11.0

enable_audio_bell no

background #333333
foreground #eeeeee

copy_on_select clipboard

term xterm-256color

map ctrl+plus change_font_size all +1.0
map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

map shift+enter send_text all \n
