background_opacity 1.0

cursor_shape block
shell_integration no-cursor

window_padding_width 0

scrollback_lines 100000

font_family DejaVuSansM Nerd Font Mono
bold_font DejaVuSansM Nerd Font Mono Bold
italic_font DejaVuSansM Nerd Font Mono Oblique
bold_italic_font DejaVuSansM Nerd Font Mono Bold Oblique
font_size 11.0
text_composition_strategy legacy

enable_audio_bell no

background #333333
foreground #eeeeee

color0  #181818
color1  #ac4242
color2  #90a959
color3  #f4bf75
color4  #6a9fb5
color5  #aa759f
color6  #75b5aa
color7  #d8d8d8
color8  #6b6b6b
color9  #c55555
color10 #aac474
color11 #feca88
color12 #82b8c8
color13 #c28cb8
color14 #93d3c3
color15 #f8f8f8

copy_on_select clipboard

term xterm-256color

map ctrl+plus change_font_size all +1.0
map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

map shift+enter send_text all \n

map ctrl+shift+enter launch --type=os-window --cwd=current
