#!/bin/sh

command -v acpi_listen >/dev/null || exit 1
command -v notify-send >/dev/null || exit 1

cmd='
function notify(msg)
{
    system("notify-send -t 1000 -u low ACPI \""msg"\"");
}
/jack\/headphone/{ notify("jack "$3"ged"); }
/ac_adapter/{notify("A/C "((index($4, "1") == 0) ? "unplugged" : "plugged")); }
'

acpi_listen | awk "$cmd"
