#!/bin/bash

IMAGE="$(mktemp).png"

grim $IMAGE

case $1 in
    "blurred")
        convert $IMAGE -filter Gaussian -resize 20% -define filter:sigma=1.5 -resize 500% $IMAGE
        swaylock -i $IMAGE
        ;;
    *|"pixelated")
        convert $IMAGE -scale 2% -scale 5000% $IMAGE
        swaylock -i $IMAGE
        ;;
esac

rm $IMAGE
