#!/bin/bash


FIELD=$1 # window field to search
VALUE=$2 # value to match in FIELD
BINARY=$3 # command line or binary path

cur_id=$(swaymsg -t get_tree | jq ".. | objects | select(.focused == true) | .window" | head -1)
dst_id=$(swaymsg -t get_tree | jq ".. | objects | select(.window_properties.$FIELD == \"$VALUE\") | .window" | head -1)

if [ -z $dst_id ]; then
    $BINARY&
elif [ $cur_id -eq $dst_id ]; then
    i3-msg "[id=$dst_id] move scratchpad"
else
    i3-msg "[id=$dst_id] focus"
fi
