[terminal.shell]
program = "/bin/zsh"

[window]
opacity = 1.0
padding = { x = 0, y = 0 }

[scrolling]
history = 100000

[font]
normal = { family = "DejaVuSansM Nerd Font Mono", style = "Regular" }
bold = { family = "DejaVuSansM Nerd Font Mono", style = "Bold" }
italic = { family = "DejaVuSansM Nerd Font Mono", style = "Italic" }
bold_italic = { family = "DejaVuSansM Nerd Font Mono", style = "Bold Italic" }
size = 11.0

[bell]
animation = "Linear"
duration = 0

[colors.primary]
background = "#333333"
foreground = "#eeeeee"

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
command = "xdg-open"
post_processing = true
mouse.enabled = true
mouse.mods = "Control"
binding.key = "U"
binding.mods = "Control|Shift"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\n"

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"
